apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-store
  namespace: external-secrets
spec:
  provider:
    gcpsm: # gcpsm provider
      auth:
        secretRef:
          privatekey:
            name: gcpsm-secret              # secret name containing SA key
            key: secret-access-credentials  # key name containing SA key
      projectID: scientific-base-418013                # name of Google Cloud project