apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  project: cluster-wide-apps
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.20
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true

---

#apiVersion: external-secrets.io/v1beta1
#kind: SecretStore
#metadata:
#  name: gcp-store
#  namespace: external-secrets
#spec:
#  provider:
#    gcpsm: # gcpsm provider
#      auth:
#        secretRef:
#          secretAccessKeySecretRef:
#            name: gcpsm-secret              # secret name containing SA key
#            key: secret-access-credentials  # key name containing SA key
#      projectID: kubernetes                 # name of Google Cloud project