apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  project: cluster-wide-apps
  source:
    chart: actions-runner-controller
    repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    targetRevision: 0.23.7
    helm:
      releaseName:
      values: |
        authSecret:
          enabled : true
          create: true
        githubWebhookServer:
          enabled: false
        env:
          - name: GITHUB_APP_ID
            valueFrom:
              secretKeyRef:
                key: github_app_id
                name: gha-secret
          - name: GITHUB_APP_INSTALLATION_ID
            valueFrom:
              secretKeyRef:
                key: github_app_installation_id
                name: gha-secret
          - name: GITHUB_APP_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                key: github_app_private_key
                name: gha-secret

  destination:
    server: https://kubernetes.default.svc
    namespace: arc-systems
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      #      https://github.com/actions/actions-runner-controller/issues/2565
      - ServerSideApply=true
