apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  project: cluster-wide-apps
  source:
    chart: arc-runner-set
    repoURL: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
    targetRevision: 0.9.3
    helm:
      releaseName:
      values: |
        githubConfigUrl : https://github.com/KanameImaichi/fivem-serverlist
        githubConfigSecret: arc-secret

  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true