apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  namespace: monitoring
spec:
  ports:
    - name: http-web
      port: 80
      protocol: TCP
      targetPort: server
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus-grafana

  type: LoadBalancer
  loadBalancerIP: 172.16.3.241
