apiVersion: v1
kind: Service
metadata:
  name: prometheus-lb
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: server
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus-server
  type: LoadBalancer
