apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gha-gcp-store
  namespace: server-list
spec:
  provider:
    gcpsm: # gcpsm provider
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret              # secret name containing SA key
            key: secret-access-credentials  # key name containing SA key
      projectID: scientific-base-418013                # name of Google Cloud project

# todo token使う