apiVersion: v1
kind: Service
metadata:
  name: node-port
spec:
  selector:
    app: minecraft-server
  ports:
  - name: minecraft
    port: 25565
    protocol: TCP
    targetPort: 25565
  type: NodePort
