apiVersion: v1
kind: Pod
metadata:
  labels:
    run: next
  name: next
spec:
  containers:
    - image: asia-northeast1-docker.pkg.dev/scientific-base-418013/server-list/app
      name: next
      env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: controller-manager
              key: database-url

