apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mc-test
  namespace: argocd
spec:
  description: mc-test yeahyeah
  sourceRepos:
    - '*'
  destinations:
    - namespace: mc-test
      server: https://kubernetes.default.svc
    # Application 及び ApplicationSet リソースは
    # argocd namespace に置かないとArgoCDに認識されないため、
    # argocd namespace へのデプロイも許可する。
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
