apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-wide-apps
  namespace: argocd
spec:
  description: The project of applications used by the entire cluster
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'cluster-wide-apps'
      server: https://kubernetes.default.svc
    # k8s-manifests/apps/ で定義されている各種アプリケーションが稼働に必要なリソースのインストールを行う
    # そのため、project側でリソース追加先のnamespaceへの変更を明示的に許可する必要がある
    - namespace: 'synology-csi'
      server: https://kubernetes.default.svc
    - namespace: 'monitoring'
      server: https://kubernetes.default.svc
    - namespace: "democratic-csi"
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fivem
  namespace: argocd
spec:
  description: fivem yeahyeah
  sourceRepos:
    - '*'
  destinations:
    - namespace: fivem
      server: https://kubernetes.default.svc
    # Application 及び ApplicationSet リソースは
    # argocd namespace に置かないとArgoCDに認識されないため、
    # argocd namespace へのデプロイも許可する。
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
