apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: controller-manager
  namespace: actions-runner-system
spec:
  refreshInterval: 1h             # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: SecretStore
    name: gha-gcp-store               # name of the SecretStore (or kind specified)
  data:
    - secretKey: github_token
      remoteRef:
        key: github_token