apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runnerdeploy
  namespace: external-secrets
spec:
  replicas: 1
  template:
    spec:
      repository: KanameImaichi/fivem-serverlist
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: github_token
              name: gha-secret
