name: Terraform apply
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
env:
  GCP_PROJECT_ID: scientific-base-418013
  GCP_PROJECT_NUMBER: 879914464587
jobs:
  tf_apply:
    name: tf apply
    runs-on: ubuntu-latest

    concurrency: tf_apply_on_main

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.2.1

      #      - name: Open tunnel to OnP k8s cluster
      #        run: bash "./.github/workflows/scripts/open-tunnel-to-onp-k8s.sh"
      - name: loud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - id: auth
        name: "Authenticate to Google Cloud"
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/${{ env.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-action-deploy-pool-infra/providers/github-actions-provider-infra"
          service_account: "github-actions-deployer@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
          access_token_lifetime: 1200s

      - run: terraform init
        working-directory: "./terraform"

      - name: Terraform apply
        run: terraform apply -input=false -no-color -auto-approve -lock-timeout=10m
        working-directory: "./terraform"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
