name: Terraform plan
on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  tf_apply:
    name: tf apply
    runs-on: ubuntu-latest

    concurrency: tf_apply_on_main

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.2.1

      #      - name: Open tunnel to OnP k8s cluster
      #        run: bash "./.github/workflows/scripts/open-tunnel-to-onp-k8s-and-export-tf-var-to-github-env.sh"
      #
      #      - name: Expose all Terraform variables to environment variables from secrets
      #        run: bash "./.github/workflows/scripts/expose-all-tf-vars-to-github-env.sh"
      #        env:
      #          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - run: terraform init
        working-directory: "./terraform"

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Comment PR
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outputs.stdout }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outputs.stdout }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outputs.stdout }}\``;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Terraform checks in directory '${{ matrix.directory }}'\n` + output
            })
