name: Terraform apply
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  tf_apply:
    name: tf apply
    runs-on: ubuntu-latest

    concurrency: tf_apply_on_main

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.2.1

      #      - name: Open tunnel to OnP k8s cluster
      #        run: bash "./.github/workflows/scripts/open-tunnel-to-onp-k8s.sh"


      - run: terraform init
        working-directory: "./terraform"

      - name: Terraform apply
        run: terraform apply -input=false -no-color -auto-approve -lock-timeout=10m
        working-directory: "./terraform"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
