apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # cascade deletion on this App deletion
spec:
  project: cluster-wide-apps
  source:
    chart: democratic-csi
    repoURL: https://democratic-csi.github.io/charts/
    targetRevision: 0.14.6
    helm:
      releaseName: truenas-iscsi
      # https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-blackbox-exporter/values.yaml
      values: |
        csiDriver:
          name: "org.democratic-csi.iscsi"
        storageClasses:
          - name: truenas-iscsi-csi
            defaultClass: true
            reclaimPolicy: Retain
            volumeBindingMode: Immediate
            allowVolumeExpansion: true
            parameters:
              fsType: ext4
            mountOptions: []
            secrets:
              provisioner-secret:
              controller-publish-secret:
              node-stage-secret:
              node-publish-secret:
              controller-expand-secret:
        driver:
          config:
            driver: freenas-iscsi 
            httpConnection:
              protocol: http
              host: 192.168.0.5
              port: 80
              username: root
              password: PASSWORD
            sshConnection:
              host: 192.168.0.5
              port: 22
              username: root
              password: PASSWORD
            zfs:
              datasetParentName: main/k8s/p
              detachedSnapshotsDatasetParentName: main/k8s/s
              datasetEnableQuotas: true
              datasetEnableReservation: false
              datasetPermissionsMode: "0777"
              datasetPermissionsUser: 0
              datasetPermissionsGroup: 0
            iscsi:
              targetPortal: 192.168.0.5:3260
              namePrefix: csi-
              targetGroups:
                - targetGroupPortalGroup: 1
                  targetGroupInitiatorGroup: 1
                  targetGroupAuthType: None
                  targetGroupAuthGroup:
              extentInsecureTpc: true
              extentXenCompat: false
              extentDisablePhysicalBlocksize: true
              extentBlocksize: 4096
              extentRpm: "SSD"
              extentAvailThreshold: 0
  destination:
    server: https://kubernetes.default.svc
    namespace: democratic-csi
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true